### ISSUE TITLE
Plugin fails to compile on Unity 6.5 / missing support for EntityId

### ISSUE THREAD

**Issue by viitana** [AnkleBreaker-Studio/unity-mcp-plugin#14]
Hello!

First off, thank you for publishing this project. It seems like a genuinely robust MCP implementation for Unity.

However, upon installing the plugin on Unity 6.5 which entered beta since the start of the year, I noticed it fails to compile. In 6.5 the deprecated "instance ID" type for Unity objects was completely removed in favour of the new EntityId identifiers. It seems like this project has yet to migrate.

https://discussions.unity.com/t/planned-breaking-changes-in-unity-6-5-updated-2026-03-27

A couple of example compile errors after a fresh import on Unity 6000.5.0b3 just to illustrate:
```
Library/PackageCache/com.anklebreaker.unity-mcp@f40a5c771e16/Editor/MCPAudioCommands.cs(19,37): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

Library/PackageCache/com.anklebreaker.unity-mcp@f40a5c771e16/Editor/MCPGraphicsCommands.cs(37,22): error CS0619: 'AssetPreview.IsLoadingAssetPreview(int)' is obsolete: 'IsLoadingAssetPreview(int instanceID) is deprecated. Use IsLoadingAssetPreview(EntityId entityId) instead.'

Library/PackageCache/com.anklebreaker.unity-mcp@f40a5c771e16/Editor/MCPSearchCommands.cs(371,33): error CS0619: 'SerializedProperty.objectReferenceInstanceIDValue' is obsolete: 'objectReferenceInstanceIDValue is obsolete. Use objectReferenceEntityIdValue instead'

Library/PackageCache/com.anklebreaker.unity-mcp@f40a5c771e16/Editor/MCPTerrainCommands.cs(1660,26): error CS0619: 'EditorUtility.InstanceIDToObject(int)' is obsolete: 'InstanceIDToObject(int) is obsolete. Use EditorUtility.EntityIdToObject instead.'
```
